import type { CatalogExercise } from "../types/catalog";

/**
 * Catálogo canónico de ejercicios.
 *
 * Los 22 videos fueron verificados uno por uno contra la API oEmbed de YouTube
 * (existencia + título coincidente con el ejercicio) el 2026-08-04. No hay
 * enlaces a búsquedas ni URLs inventadas: un ejercicio sin `videoUrl` se muestra
 * como "Video por agregar".
 *
 * Los thumbnails se derivan del mismo ID verificado, no se inventan.
 */

/** Construye la URL del video a partir de un ID ya verificado. */
const video = (id: string) => `https://www.youtube.com/watch?v=${id}`;
/** Miniatura oficial del mismo video verificado. */
const thumb = (id: string) => `https://img.youtube.com/vi/${id}/hqdefault.jpg`;

const withMedia = (
  id: string,
  exercise: Omit<CatalogExercise, "videoUrl" | "thumbnailUrl">,
): CatalogExercise => ({
  ...exercise,
  videoUrl: video(id),
  thumbnailUrl: thumb(id),
});

export const EXERCISE_CATALOG: CatalogExercise[] = [
  withMedia("mwlp75MS6Rg", {
    id: "plancha-abdominal",
    nameEs: "Plancha abdominal",
    nameOriginal: "Plank",
    pattern: "core",
    primaryMuscles: ["Recto abdominal", "Transverso", "Oblicuos"],
    level: "beginner",
    equipment: ["Peso corporal"],
    techniqueCues: [
      "Codos bajo los hombros y antebrazos paralelos",
      "Aprieta glúteos y mete la pelvis para borrar el arco lumbar",
      "Respira sin soltar la tensión del abdomen",
    ],
    commonMistakes: ["Cadera muy alta", "Zona lumbar hundida", "Aguantar la respiración"],
    easierAlternative: "Plancha con rodillas apoyadas",
    harderAlternative: "Plancha con peso en la espalda o RKC plank",
  }),
  withMedia("L9KZfxT654Y", {
    id: "puente-gluteos",
    nameEs: "Puente de glúteos",
    nameOriginal: "Glute Bridge",
    pattern: "hinge",
    primaryMuscles: ["Glúteo mayor", "Isquiotibiales"],
    level: "beginner",
    equipment: ["Peso corporal"],
    techniqueCues: [
      "Talones cerca del glúteo y punta del pie relajada",
      "Empuja con los talones y termina apretando el glúteo arriba",
      "Costillas abajo: no compenses con la lumbar",
    ],
    commonMistakes: ["Arquear la lumbar en vez de extender la cadera", "Empujar con la punta del pie"],
    easierAlternative: "Puente isométrico de 5 segundos por repetición",
    harderAlternative: "Puente a una pierna o hip thrust con barra",
  }),
  withMedia("t4Zz6-aG8Iw", {
    id: "hip-90-90",
    nameEs: "90/90 de cadera",
    nameOriginal: "90/90 Hip Stretch",
    pattern: "mobility",
    primaryMuscles: ["Rotadores de cadera", "Glúteo medio", "Psoas"],
    level: "beginner",
    equipment: ["Peso corporal"],
    techniqueCues: [
      "Ambas rodillas a 90 grados, pelvis sentada y estable",
      "Lleva el pecho sobre la tibia delantera con espalda larga",
      "Cambia de lado rotando desde la cadera, no desde la rodilla",
    ],
    commonMistakes: ["Redondear la espalda para llegar más lejos", "Forzar la rodilla en vez de la cadera"],
    easierAlternative: "Apoyar las manos en un banco para reducir el rango",
    harderAlternative: "90/90 con transición sin manos",
  }),
  withMedia("G-bxQY57mKc", {
    id: "box-jump",
    nameEs: "Box Jump",
    nameOriginal: "Box Jump",
    pattern: "jump",
    primaryMuscles: ["Cuádriceps", "Glúteos", "Gemelos"],
    level: "intermediate",
    equipment: ["Cajón"],
    techniqueCues: [
      "Cae suave, con rodillas y cadera flexionadas para absorber",
      "Rodillas alineadas con los pies al aterrizar",
      "Baja del cajón caminando, nunca saltando",
    ],
    commonMistakes: [
      "Buscar un cajón demasiado alto y aterrizar encogido",
      "Aterrizar rígido con las rodillas hacia dentro",
      "Bajar de un salto y acumular impacto",
    ],
    easierAlternative: "Salto al cajón bajo o step-up explosivo",
    harderAlternative: "Box jump a una pierna",
  }),
  withMedia("BR4tlEE_A98", {
    id: "goblet-squat",
    nameEs: "Sentadilla Goblet",
    nameOriginal: "Goblet Squat",
    pattern: "squat",
    primaryMuscles: ["Cuádriceps", "Glúteos", "Core"],
    level: "beginner",
    equipment: ["Mancuerna", "Kettlebell"],
    techniqueCues: [
      "Peso pegado al pecho y codos dentro de las rodillas",
      "Baja entre los talones manteniendo el torso vertical",
      "Empuja el suelo con todo el pie al subir",
    ],
    commonMistakes: ["Talones que se levantan", "Rodillas que colapsan hacia dentro", "Perder la vertical del torso"],
    easierAlternative: "Sentadilla a cajón",
    harderAlternative: "Sentadilla frontal con barra",
  }),
  withMedia("sK4Rvug6ufo", {
    id: "press-inclinado-mancuernas",
    nameEs: "Press inclinado con mancuernas",
    nameOriginal: "Incline Dumbbell Bench Press",
    pattern: "push",
    primaryMuscles: ["Pectoral superior", "Deltoides anterior", "Tríceps"],
    level: "intermediate",
    equipment: ["Mancuernas", "Banco inclinado"],
    techniqueCues: [
      "Banco entre 30 y 45 grados, omóplatos apretados atrás",
      "Codos a unos 45 grados del torso, no abiertos del todo",
      "Baja controlado hasta sentir estiramiento en el pecho",
    ],
    commonMistakes: ["Inclinación excesiva que convierte el press en hombro", "Rebotar las mancuernas arriba"],
    easierAlternative: "Press inclinado en máquina o con menor inclinación",
    harderAlternative: "Press inclinado con pausa de 2 segundos abajo",
  }),
  withMedia("2C-uNgKwPLE", {
    id: "split-squat-bulgaro",
    nameEs: "Split Squat Búlgaro",
    nameOriginal: "Bulgarian Split Squat",
    pattern: "lunge",
    primaryMuscles: ["Cuádriceps", "Glúteos", "Estabilizadores de cadera"],
    level: "intermediate",
    equipment: ["Mancuernas", "Banco"],
    techniqueCues: [
      "Pie trasero sobre el banco, empeine relajado",
      "Distancia suficiente para que la rodilla delantera no se adelante en exceso",
      "Baja vertical y sube empujando con el talón delantero",
    ],
    commonMistakes: ["Paso muy corto que carga la rodilla", "Perder el equilibrio por base muy angosta"],
    easierAlternative: "Split squat con pie trasero en el suelo",
    harderAlternative: "Búlgaro con déficit o con mayor carga",
  }),
  withMedia("W3fZzhw87ak", {
    id: "remo-unilateral",
    nameEs: "Remo unilateral con mancuerna",
    nameOriginal: "Single Arm Dumbbell Row",
    pattern: "pull",
    primaryMuscles: ["Dorsal ancho", "Romboides", "Trapecio medio"],
    level: "beginner",
    equipment: ["Mancuerna", "Banco"],
    techniqueCues: [
      "Espalda plana y cadera en bisagra, no redondeada",
      "Tira con el codo hacia la cadera, no con la mano",
      "Evita rotar el torso para levantar más peso",
    ],
    commonMistakes: ["Rotar el tronco en cada repetición", "Encoger el hombro hacia la oreja"],
    easierAlternative: "Remo con apoyo de pecho en banco inclinado",
    harderAlternative: "Remo unilateral sin apoyo, en posición de bisagra",
  }),
  withMedia("lLAw6fUccKA", {
    id: "farmers-walk",
    nameEs: "Farmer's Walk",
    nameOriginal: "Farmer's Carry",
    pattern: "carry",
    primaryMuscles: ["Agarre", "Trapecios", "Core"],
    level: "beginner",
    equipment: ["Mancuernas", "Kettlebells"],
    techniqueCues: [
      "Pecho alto, hombros atrás y abajo",
      "Pasos cortos y controlados, sin balancear el peso",
      "Aprieta el mango como si quisieras dejar huella",
    ],
    commonMistakes: ["Caminar inclinado hacia un lado", "Dejar caer los hombros hacia adelante"],
    easierAlternative: "Carga a una mano con menos peso y distancia corta",
    harderAlternative: "Farmer's walk con agarre grueso o peso máximo",
  }),
  withMedia("dBAmQ9bx3JA", {
    id: "pallof-press",
    nameEs: "Pallof Press",
    nameOriginal: "Pallof Press",
    pattern: "core",
    primaryMuscles: ["Oblicuos", "Transverso", "Glúteo medio"],
    level: "beginner",
    equipment: ["Banda elástica", "Polea"],
    techniqueCues: [
      "Perpendicular al anclaje, pies al ancho de hombros",
      "Extiende los brazos sin dejar que el torso rote",
      "Aprieta glúteos para bloquear la pelvis",
    ],
    commonMistakes: ["Dejar que el torso gire hacia el anclaje", "Usar tanta resistencia que se pierde la postura"],
    easierAlternative: "Pallof press de rodillas o con menos resistencia",
    harderAlternative: "Pallof press con paso lateral o en posición dividida",
  }),
  withMedia("-CiWQ2IvY34", {
    id: "worlds-greatest-stretch",
    nameEs: "World's Greatest Stretch",
    nameOriginal: "World's Greatest Stretch",
    pattern: "mobility",
    primaryMuscles: ["Flexores de cadera", "Isquiotibiales", "Columna torácica"],
    level: "beginner",
    equipment: ["Peso corporal"],
    techniqueCues: [
      "Zancada larga con la mano al interior del pie delantero",
      "Rota abriendo el pecho hacia la rodilla adelantada",
      "Termina estirando el isquiotibial llevando la cadera atrás",
    ],
    commonMistakes: ["Rotar desde la lumbar en vez de la torácica", "Hacerlo demasiado rápido"],
    easierAlternative: "Apoyar la rodilla trasera en el suelo",
    harderAlternative: "Añadir pausa de 3 segundos en cada rotación",
  }),
  withMedia("ZdAHe9_HeEw", {
    id: "bird-dog",
    nameEs: "Bird Dog",
    nameOriginal: "Bird Dog",
    pattern: "core",
    primaryMuscles: ["Erectores espinales", "Glúteos", "Core"],
    level: "beginner",
    equipment: ["Peso corporal"],
    techniqueCues: [
      "Manos bajo los hombros y rodillas bajo la cadera",
      "Extiende brazo y pierna contrarios sin mover la pelvis",
      "Imagina un vaso de agua sobre la zona lumbar",
    ],
    commonMistakes: ["Rotar la cadera al subir la pierna", "Subir el brazo más allá de la línea del hombro"],
    easierAlternative: "Extender sólo el brazo o sólo la pierna",
    harderAlternative: "Bird dog con banda o llevando codo y rodilla al centro",
  }),
  withMedia("bxn9FBrt4-A", {
    id: "dead-bug",
    nameEs: "Dead Bug",
    nameOriginal: "Dead Bug",
    pattern: "core",
    primaryMuscles: ["Transverso", "Recto abdominal"],
    level: "beginner",
    equipment: ["Peso corporal"],
    techniqueCues: [
      "Lumbar pegada al suelo durante todo el movimiento",
      "Baja brazo y pierna contrarios lento y exhalando",
      "Si la lumbar se despega, reduce el rango",
    ],
    commonMistakes: ["Arquear la lumbar al extender", "Ir demasiado rápido"],
    easierAlternative: "Mover sólo las piernas, con brazos apoyados",
    harderAlternative: "Dead bug con banda o con peso en las manos",
  }),
  withMedia("6cXVxLqTQM8", {
    id: "kettlebell-swing",
    nameEs: "Kettlebell Swing",
    nameOriginal: "Hardstyle Kettlebell Swing",
    pattern: "hinge",
    primaryMuscles: ["Glúteos", "Isquiotibiales", "Core"],
    level: "intermediate",
    equipment: ["Kettlebell"],
    techniqueCues: [
      "Es una bisagra de cadera, no una sentadilla",
      "La pesa flota por el impulso de la cadera, no la levantan los brazos",
      "Termina de pie, apretando glúteos y abdomen",
    ],
    commonMistakes: ["Sentadillar en vez de bisagrar", "Levantar la pesa con los hombros", "Hiperextender la lumbar arriba"],
    easierAlternative: "Bisagra de cadera con banda o swing a media altura",
    harderAlternative: "Swing a una mano",
  }),
  withMedia("tpUKFfIFG24", {
    id: "trap-bar-deadlift",
    nameEs: "Peso muerto con barra hexagonal",
    nameOriginal: "Trap Bar Deadlift",
    pattern: "hinge",
    primaryMuscles: ["Glúteos", "Cuádriceps", "Espalda baja"],
    level: "intermediate",
    equipment: ["Barra hexagonal"],
    techniqueCues: [
      "Pecho alto y espalda neutra antes de despegar",
      "Empuja el suelo con los pies en vez de tirar con la espalda",
      "Bloquea cadera y rodillas al mismo tiempo arriba",
    ],
    commonMistakes: ["Redondear la espalda al iniciar", "Subir primero la cadera y dejar atrás el pecho"],
    easierAlternative: "Peso muerto desde bloques para reducir el rango",
    harderAlternative: "Trap bar con déficit o tempo controlado",
  }),
  withMedia("uhghy9pFIPY", {
    id: "peso-muerto-rumano",
    nameEs: "Peso Muerto Rumano",
    nameOriginal: "Romanian Deadlift",
    pattern: "hinge",
    primaryMuscles: ["Isquiotibiales", "Glúteos", "Erectores"],
    level: "intermediate",
    equipment: ["Barra", "Mancuernas"],
    techniqueCues: [
      "Rodillas apenas flexionadas y fijas",
      "Lleva la cadera hacia atrás manteniendo la barra pegada a la pierna",
      "Baja hasta sentir el estiramiento del isquiotibial, no más",
    ],
    commonMistakes: ["Convertirlo en sentadilla", "Redondear la espalda buscando más rango"],
    easierAlternative: "RDL con mancuernas y rango parcial",
    harderAlternative: "RDL a una pierna",
  }),
  withMedia("YI_VHFjfB-g", {
    id: "press-militar-mancuernas",
    nameEs: "Press militar con mancuernas",
    nameOriginal: "Dumbbell Overhead Press",
    pattern: "push",
    primaryMuscles: ["Deltoides", "Tríceps", "Core"],
    level: "intermediate",
    equipment: ["Mancuernas"],
    techniqueCues: [
      "Costillas abajo y glúteos apretados para no arquear",
      "Empuja en línea recta, terminando con las mancuernas sobre los hombros",
      "Baja hasta la altura de la barbilla con control",
    ],
    commonMistakes: ["Arquear la lumbar para compensar falta de movilidad", "Empujar hacia adelante en vez de arriba"],
    easierAlternative: "Press sentado con respaldo",
    harderAlternative: "Press de pie a una mano",
  }),
  withMedia("vOiHvzj5XhA", {
    id: "step-up",
    nameEs: "Step-up",
    nameOriginal: "Step Up",
    pattern: "lunge",
    primaryMuscles: ["Cuádriceps", "Glúteos"],
    level: "beginner",
    equipment: ["Cajón", "Mancuernas"],
    techniqueCues: [
      "Apoya todo el pie sobre el cajón, no sólo la punta",
      "Sube empujando con la pierna de arriba, sin impulsarte con la de abajo",
      "Baja controlado, sin dejarte caer",
    ],
    commonMistakes: ["Impulsarse con la pierna de atrás", "Cajón tan alto que obliga a inclinarse"],
    easierAlternative: "Step-up a cajón bajo sin peso",
    harderAlternative: "Step-up lento con pausa arriba o cajón más alto",
  }),
  withMedia("1rRmIzEsl_4", {
    id: "dominada",
    nameEs: "Dominada",
    nameOriginal: "Pull Up",
    pattern: "pull",
    primaryMuscles: ["Dorsal ancho", "Bíceps", "Trapecio medio"],
    level: "advanced",
    equipment: ["Barra de dominadas"],
    techniqueCues: [
      "Parte con los hombros abajo y atrás, no colgando pasivo",
      "Lleva el pecho hacia la barra guiando con los codos",
      "Baja completo controlando la bajada",
    ],
    commonMistakes: ["Balancearse para ganar impulso", "Rango parcial que no llega al mentón"],
    easierAlternative: "Dominada asistida con banda o jalón al pecho",
    harderAlternative: "Dominada con lastre",
  }),
  withMedia("CAwf7n6Luuc", {
    id: "jalon-al-pecho",
    nameEs: "Jalón al pecho",
    nameOriginal: "Lat Pulldown",
    pattern: "pull",
    primaryMuscles: ["Dorsal ancho", "Bíceps", "Romboides"],
    level: "beginner",
    equipment: ["Polea alta"],
    techniqueCues: [
      "Agarre algo más ancho que los hombros",
      "Lleva la barra al pecho alto, con el torso ligeramente atrás",
      "Piensa en bajar los codos hacia los bolsillos",
    ],
    commonMistakes: ["Jalar detrás de la nuca", "Usar impulso del torso en cada repetición"],
    easierAlternative: "Jalón con agarre neutro y menos carga",
    harderAlternative: "Dominada estricta",
  }),
  withMedia("PlAE67ovNEo", {
    id: "dead-hang",
    nameEs: "Colgado en barra (Hangs)",
    nameOriginal: "Dead Hang",
    pattern: "grip",
    primaryMuscles: ["Antebrazos", "Agarre", "Dorsal"],
    level: "beginner",
    equipment: ["Barra de dominadas"],
    techniqueCues: [
      "Agarre firme con el pulgar rodeando la barra",
      "Hombros activos, sin quedar colgando totalmente pasivo",
      "Respira y controla el tiempo bajo tensión",
    ],
    commonMistakes: ["Colgar completamente pasivo desde el primer segundo", "Soltar el pulgar"],
    easierAlternative: "Colgado con los pies apoyados en el suelo",
    harderAlternative: "Colgado a una mano o con lastre",
  }),
  withMedia("7C8-zj3nRro", {
    id: "thread-the-needle",
    nameEs: "Plancha con rotación (Thread the Needle)",
    nameOriginal: "Thread the Needle",
    pattern: "mobility",
    primaryMuscles: ["Columna torácica", "Dorsal", "Hombro posterior"],
    level: "beginner",
    equipment: ["Peso corporal"],
    techniqueCues: [
      "Desde cuadrupedia, pasa el brazo por debajo del torso",
      "Rota abriendo el pecho al techo, no forzando el cuello",
      "Mantén la cadera quieta sobre las rodillas",
    ],
    commonMistakes: ["Rotar desde la lumbar", "Mover la cadera para ganar rango"],
    easierAlternative: "Rotación torácica sentado sobre los talones",
    harderAlternative: "Rotación en posición de plancha alta",
  }),
];

/** Índice por ID para resolver `catalogExerciseId` sin recorrer el arreglo. */
export const EXERCISE_BY_ID: Record<string, CatalogExercise> = Object.fromEntries(
  EXERCISE_CATALOG.map((exercise) => [exercise.id, exercise]),
);

export function findExercise(catalogExerciseId: string): CatalogExercise | undefined {
  return EXERCISE_BY_ID[catalogExerciseId];
}

/** IDs válidos, para que el agente sólo pueda elegir de aquí. */
export const CATALOG_IDS = EXERCISE_CATALOG.map((exercise) => exercise.id);
